### ISSUE TITLE
Duplicated a media rules in css

### ISSUE THREAD

**Issue by EugenGedroyc** [SassNinja/postcss-extract-media-query#29]
my postcss configuration in laravel mix:
```
postCss: [
    require('postcss-extract-media-query')({
		output: {
		  path: path.join(__dirname, '/public/css'), 
		  name: '[query].css'
		},
		queries: {
		  'only screen and (min-width: 1023px)': 'desktop',
		  'only screen and (min-width: 1460px)': 'desktop',
		  'only screen and (min-width: 1800px)': 'desktop',
		  'only screen and (min-width: 1870px)': 'desktop',
		  'only screen and (min-width: 2100px)': 'desktop',
		  'only screen and (min-width: 2400px)': 'desktop'
		},
		extractAll: false
    }),
  ],
```
Created desktop.css with all queries but thes repeating. The queries save in desktop.css first time and then second time the same way after first time. 'postcss-combine-duplicated-selectors' don't helped me
And is strange that console output three times:
```
[extracted media query] desktop.css
[extracted media query] desktop.css
[extracted media query] desktop.css
```

**Comment by nucliweb** [comment]
You need different values in the `queries` object.

Like this:

```css
postCss: [
    require('postcss-extract-media-query')({
		output: {
		  path: path.join(__dirname, '/public/css'), 
		  name: '[query].css'
		},
		queries: {
		  'only screen and (min-width: 1023px)': 'desktop-1023px',
		  'only screen and (min-width: 1460px)': 'desktop-1023px',
		  'only screen and (min-width: 1800px)': 'desktop-1800px',
		  'only screen and (min-width: 1870px)': 'desktop-1870px',
		  'only screen and (min-width: 2100px)': 'desktop-2100px',
		  'only screen and (min-width: 2400px)': 'desktop-2400px'
		},
		extractAll: false
    }),
  ],
```

Btw, depending on the contents. I think that you can use fewer queries, like:

```css
postCss: [
    require('postcss-extract-media-query')({
		output: {
		  path: path.join(__dirname, '/public/css'), 
		  name: '[query].css'
		},
		queries: {
		  'only screen and (min-width: 1023px)': 'desktop-1023px',
		  'only screen and (min-width: 1800px)': 'desktop-1800px',
		  'only screen and (min-width: 2100px)': 'desktop-2100px'
		},
		extractAll: false
    }),
  ],
